import "./globals.css";
import { Poppins } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["400", "500", "600"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en' className={poppins.className}>
			<Analytics/>
			<body>{children}</body>
		</html>
	);
}
